/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sami.ada.biblio.vista;

import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Component;

import sami.ada.biblio.modelo.Usuario;

/**
 *
 * @author Samii
 */
public class Detalles extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Detalles.class.getName());

    private final Usuario usuario;
    private transient Runnable onVolver;
    private transient Runnable onCerrarSesion;

    /**
     * Creates new form Detalles
     */
    public Detalles() {
        this(null);
    }

    public Detalles(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCubierta = new javax.swing.JLabel();
        jLabelIsbn = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAutoria = new javax.swing.JLabel();
        jLabelEditorial = new javax.swing.JLabel();
        jLabelMejorEstado = new javax.swing.JLabel();
        jLabelGeneros = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPaneReviews = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextFieldPuntuacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComentario = new javax.swing.JTextArea();
        jButtonEnviarResenna = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCubierta.setToolTipText("");
        jLabelCubierta.setVerifyInputWhenFocusTarget(false);

        jLabelIsbn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelIsbn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIsbn.setText("ISBN: XXXX-XXXX-XXXX");

        jPanel6.setLayout(new java.awt.GridLayout(3, 1, 10, 10));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Explorar obras similares");
        jPanel6.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Tomar prestado");
        jPanel6.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Añadir a préstamo");
        jPanel6.add(jButton5);

        jPanel7.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitulo.setText("Título de libro");
        jPanel7.add(jLabelTitulo);

        jLabelAutoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAutoria.setText("Autores");
        jPanel7.add(jLabelAutoria);

        jLabelEditorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelEditorial.setText("Editorial");
        jPanel7.add(jLabelEditorial);

        jLabelMejorEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelMejorEstado.setText("Mejor estado disponible");
        jPanel7.add(jLabelMejorEstado);

        jLabelGeneros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelGeneros.setText("Géneros");
        jPanel7.add(jLabelGeneros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCubierta, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabelIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelCubierta, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIsbn))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Volver");
        jPanel4.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Cerrar sesión");
        jPanel4.add(jButton2);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("X");
        jPanel5.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("/ 5");
        jPanel5.add(jLabel2);

        jTextFieldPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPuntuacionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("¡Cuéntanos sobre tu experiencia!");

        jTextAreaComentario.setColumns(20);
        jTextAreaComentario.setRows(5);
        jScrollPane1.setViewportView(jTextAreaComentario);

        jButtonEnviarResenna.setText("Enviar reseña");
        jButtonEnviarResenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarResennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jTextFieldPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEnviarResenna, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonEnviarResenna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneReviews, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPuntuacionActionPerformed

    private void jButtonEnviarResennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarResennaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnviarResennaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Detalles().setVisible(true));
    }

    public void setTitulo(String titulo) {
        setTitle("Detalles - " + titulo);
        jLabelTitulo.setText(titulo != null ? titulo : "");
    }

    public void setAutoria(String autoria) {
        jLabelAutoria.setText(autoria != null ? autoria : "");
    }

    public void setEditorial(String editorial) {
        jLabelEditorial.setText(editorial != null ? editorial : "");
    }

    public void setGeneros(String generos) {
        jLabelGeneros.setText(generos != null ? generos : "");
    }

    public void setMejorEstado(String estado) {
        jLabelMejorEstado.setText(estado != null ? estado : "");
    }

    public void setIsbn(String isbn) {
        String valor = (isbn != null && !isbn.isBlank()) ? isbn : "-";
        jLabelIsbn.setText("ISBN: " + valor);
    }

    public void setCubierta(ImageIcon icono) {
        if (icono != null) {
            Image escalada = icono.getImage().getScaledInstance(300, 450, Image.SCALE_SMOOTH);
            jLabelCubierta.setIcon(new ImageIcon(escalada));
            jLabelCubierta.setText("");
        } else {
            jLabelCubierta.setIcon(null);
            jLabelCubierta.setText("Sin portada");
        }
    }

    public void setOnVolver(Runnable onVolver) {
        this.onVolver = onVolver;
    }

    public void setOnCerrarSesion(Runnable onCerrarSesion) {
        this.onCerrarSesion = onCerrarSesion;
    }

    public javax.swing.JButton getBotonVolver() {
        return jButton1;
    }

    public javax.swing.JButton getBotonCerrarSesion() {
        return jButton2;
    }

    public JButton getBotonEnviarResenna() {
        return jButtonEnviarResenna;
    }

    public JTextField getCampoPuntuacion() {
        return jTextFieldPuntuacion;
    }

    public JTextArea getCampoComentario() {
        return jTextAreaComentario;
    }

    public void mostrarReviews(java.util.List<sami.ada.biblio.modelo.Review> reviews) {
        javax.swing.JPanel contenedor = new javax.swing.JPanel();
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.Y_AXIS));

        if (reviews != null) {
            for (sami.ada.biblio.modelo.Review review : reviews) {
                javax.swing.JPanel panel = new javax.swing.JPanel();
                panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
                panel.setAlignmentX(Component.LEFT_ALIGNMENT);
                panel.setBorder(new javax.swing.border.EmptyBorder(8, 8, 8, 8));

                javax.swing.JLabel cabecera = new javax.swing.JLabel(review.getDniUsuario() + " - " + review.getValoracion() + "/5");
                cabecera.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                cabecera.setAlignmentX(Component.LEFT_ALIGNMENT);

                javax.swing.JTextArea cuerpo = new javax.swing.JTextArea(review.getDescripcion() != null ? review.getDescripcion() : "");
                cuerpo.setWrapStyleWord(true);
                cuerpo.setLineWrap(true);
                cuerpo.setEditable(false);
                cuerpo.setOpaque(false);
                cuerpo.setBorder(null);
                cuerpo.setAlignmentX(Component.LEFT_ALIGNMENT);
                cuerpo.setFont(cuerpo.getFont().deriveFont(java.awt.Font.ITALIC));

                panel.add(cabecera);
                panel.add(javax.swing.Box.createVerticalStrut(4));
                panel.add(cuerpo);

                contenedor.add(panel);
                contenedor.add(javax.swing.Box.createVerticalStrut(8));
            }
        }

        jScrollPaneReviews.setViewportView(contenedor);
    }

    public void limpiarFormularioReview() {
        jTextFieldPuntuacion.setText("");
        jTextAreaComentario.setText("");
    }

    public void mostrarMediaValoracion(double media) {
        jLabel1.setText(String.format(java.util.Locale.US, "%.1f", media));
    }

    public Usuario getUsuario() {
        return usuario;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (onVolver != null) {
            onVolver.run();
        } else {
            dispose();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (onCerrarSesion != null) {
            onCerrarSesion.run();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonEnviarResenna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAutoria;
    private javax.swing.JLabel jLabelCubierta;
    private javax.swing.JLabel jLabelEditorial;
    private javax.swing.JLabel jLabelGeneros;
    private javax.swing.JLabel jLabelIsbn;
    private javax.swing.JLabel jLabelMejorEstado;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneReviews;
    private javax.swing.JTextArea jTextAreaComentario;
    private javax.swing.JTextField jTextFieldPuntuacion;
    // End of variables declaration//GEN-END:variables
}
