/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sami.ada.biblio.vista;

import sami.ada.biblio.controlador.ControladorVentanaLogin;
import sami.ada.biblio.modelo.DAO.Conexion;
import sami.ada.biblio.modelo.DAO.UsuarioDAO;

/**
 *
 * @author Samuel
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    private transient ControladorVentanaLogin controlador;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        var conexion = new Conexion();
        var usuarioDAO = new UsuarioDAO(conexion);
        controlador = new ControladorVentanaLogin(this, usuarioDAO);
        controlador.registrarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldContrasenna = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonRegistro = new javax.swing.JButton();
        jButtonRecContra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de Sesión");
        jPanel1.add(jLabel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setText("DNI:");
        jPanel2.add(jLabel2);

        jPanel2.add(jTextFieldDni);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 5, 0));

        jLabel3.setText("Contraseña:");
        jPanel3.add(jLabel3);

        jPasswordFieldContrasenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContrasennaActionPerformed(evt);
            }
        });
        jPanel3.add(jPasswordFieldContrasenna);

        jPanel1.add(jPanel3);

        jButtonLogin.setText("Acceder");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jButtonRegistro.setText("Registrarse");
        jButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistroActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRegistro);

        jButtonRecContra.setText("Recuperar contraseña");
        jButtonRecContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecContraActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRecContra);

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldContrasennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasennaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasennaActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {
        // El controlador está registrado como ActionListener; se deja vacío para evitar doble llamada.
    }

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {
        // Pantalla de registro sin implementación
    }

    private void jButtonRecContraActionPerformed(java.awt.event.ActionEvent evt) {
        // Pantalla de registro sin implementación
    }

    public void mostrarMensajeError(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    public void cerrar() {
        this.dispose();
    }

    // Getters para que el controlador pueda acceder a los componentes
    public javax.swing.JButton getBotonLogin() {
        return jButtonLogin;
    }

    public String getDni() {
        return jTextFieldDni.getText();
    }

    public char[] getContrasena() {
        return jPasswordFieldContrasenna.getPassword();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRecContra;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordFieldContrasenna;
    private javax.swing.JTextField jTextFieldDni;
    // End of variables declaration//GEN-END:variables
}
